### ISSUE TITLE
IsSymmetric declared as attribute rather than property

### ISSUE THREAD

**Issue by jesselansdown** [gap-packages/laguna#19]
Since IsSymmetric takes true/false values, it should be a property rather than an attribute. Moreover, it prevents IsSymmetric from being declared as a property for other GAP objects.

**Comment by jesselansdown** [comment]
Would it be possible to change this so that IsSymmetric can be declared as a property for other objects?

**Comment by olexandr-konovalov** [comment]
Thanks @jesselansdown for the suggestion and @fingolfin for the PR. This will shortly appear in the next release.

**Comment by jesselansdown** [comment]
Fantastic, thanks!

**Comment by fingolfin** [comment]
Unfortunately this caused a regression, as the numericalsgps package also declares `IsSymmetric` as an attribute (but simply because it had to in order to stay compatible with `laguna`). I'll try to address that...

**Comment by fingolfin** [comment]
See also https://github.com/gap-packages/numericalsgps/pull/69 and https://github.com/gap-packages/laguna/pull/28
