### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/laguna#26]
... ideally after merging PR #25 <s>(a fix for issue  #16 of course would also be nice, but I'dd rather first see a release, with the other fixes, and then later another with a fix for  #16)</s> -- also PR #27

Alternatively, if you prefer, I can also take care of it for you.

**Comment by olexandr-konovalov** [comment]
@fingolfin released 3.9.4 in 079393eb528ea458c89d9e83e60ae90ee03d3248
