### ISSUE TITLE
Update the FSF address

### ISSUE THREAD

**Issue by jamesjer** [gap-packages/laguna#5]
The FSF address in COPYING has not been correct since 2005, nearly 13 years ago.  The correct address is 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.  Note that this address occurs in 2 places in the file.  Also, the phrase "GNU Library General Public License" has been replaced by "GNU Lesser General Public License" in the official GPL 2.0 text; see https://www.gnu.org/licenses/old-licenses/gpl-2.0.html.

**Comment by olexandr-konovalov** [comment]
Thanks @jamesjer
